name: Push to GitLab

on: [push]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Push to GitLab
      run: |
        git remote add gitlab ${GITLAB_REPO_URL}
        git config --local http.${GITLAB_REPO_URL}/.extraheader "AUTHORIZATION: basic $(printf "x-access-token:%s" "$GITLAB_TOKEN" | base64)"
        git push -f --all gitlab
      env:
        GITLAB_REPO_URL: ${{ secrets.GITLAB_REPO_URL }}
        GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
