name: Push to GitLab

on: [push]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Push to GitLab
      run: |
        git remote add gitlab https://git:${GITLAB_TOKEN}@${GITLAB_REPO_URL#https://}
        git push -f --all gitlab
      env:
        GITLAB_REPO_URL: ${{ secrets.GITLAB_REPO_URL }}
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
